BibleVerse(Deprecated)/Controllers/BBVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using BibleVerse.DTO;
using Newtonsoft.Json;
using System.Net.Http;
using BibleVerse.Helper;
using System.Text;
using System.Net;
using System.IO;
using BVCommon;

namespace BibleVerse.Controllers
{
    public class BBVController : Controller
    {

        BibleVerseAPI _api = new BibleVerseAPI();
        SignInManager<Users> signInManager;

        public BBVController(SignInManager<Users> _signInManager)
        {
            signInManager = _signInManager;
        }


        public async Task<IActionResult> Index(UserViewModel user)
        {
            if (HttpContext.Session.GetString("user") == null)
            {
                return RedirectToAction("Login", "Home");
            }

            //Get Users Posts
            HttpClient client = _api.Initial();
            var userName = JsonConvert.DeserializeObject<Users>(HttpContext.Session.GetString("user"));
            var result = await client.GetAsync("Post/GetTimeline?userName=" + userName.UserName);

            //Verify user was created
            var r = result.Content.ReadAsStringAsync();


            if(r.IsCompletedSuccessfully)
            {
                HttpContext.Session.SetString("posts", r.Result);
            } else
            {
                HttpContext.Session.SetString("posts", "An errr occured while retrieving your posts");
            }

            return View();
        }

        public async Task<IActionResult> Account(UserViewModel user)
        {
            if (HttpContext.Session.GetString("user") == null)
            {
                return RedirectToAction("Login", "Home");
            }

            //Get call to retrieve users profile

            HttpClient client = _api.Initial();
            var userName = JsonConvert.DeserializeObject<Users>(HttpContext.Session.GetString("user"));
            var result = await client.GetAsync("Post/Profile?userID=" + userName.UserName);
            var r = result.Content.ReadAsStringAsync();

            if(r.IsCompletedSuccessfully)
            {
                if (result.ReasonPhrase == "OK")
                {
                    ApiResponseModel response = JsonConvert.DeserializeObject<ApiResponseModel>(r.Result);
                    HttpContext.Session.SetString("profile", response.ResponseBody[0]);
                    HttpContext.Session.SetString("posts", response.ResponseBody[3]);

                } else
                {
                    //Send user to Error page
                    RedirectToAction("Login", "Home");
                }
            } else
            {
                RedirectToAction("Login", "Home");
            }  

            return View("Account/Account");
        }

        [HttpGet]
        public async Task<IActionResult> Search(string SearchBox)
        {
            if (HttpContext.Session.GetString("user") == null)
            {
                return RedirectToAction("Login", "Home");
            }

            UserViewModel u = JsonConvert.DeserializeObject<UserViewModel>(HttpContext.Session.GetString("user"));

            HttpClient client = _api.Initial();
            var result = await client.GetAsync("Registration/Search?user=" + u.UserID + "&username=" + SearchBox);
            ApiResponseModel response = JsonConvert.DeserializeObject<ApiResponseModel>(result.Content.ReadAsStringAsync().Result);

            if (result.StatusCode == HttpStatusCode.OK)
            {
                List<SearchViewModel> searchResults = JsonConvert.DeserializeObject<List<SearchViewModel>>(response.ResponseBody[0]);
                ViewBag.SearchResults = searchResults;
                return View();
            }
            else if(result.StatusCode == HttpStatusCode.Conflict)
            {
                //Return search screen with failed message passed via ViewBag
                ViewBag.Errors = response.ResponseErrors;
                return View();
            } else
            {
                List<string> e = new List<string>();
                e.Add("An unexpected error occurred. Please try again");
                ViewBag.Errors = e;
                return View();
            }

        }

        [HttpGet]
        public async Task<IActionResult> Profile(string username)
        {
            if (HttpContext.Session.GetString("user") != null)
            {
                UserViewModel u = JsonConvert.DeserializeObject<UserViewModel>(HttpContext.Session.GetString("user"));

    
                    HttpClient client = _api.Initial();
                    var result = await client.GetAsync("Post/Profile?userID=" + username + "&currUserName=" + u.UserName);
                    var r = result.Content.ReadAsStringAsync();

                    ApiResponseModel response = JsonConvert.DeserializeObject<ApiResponseModel>(r.Result);

                    ViewBag.UserProfile = response.ResponseBody[0];
                    ViewBag.UserViewModel = response.ResponseBody[1];
                    ViewBag.RequestResult = response.ResponseBody[2];
                    HttpContext.Session.SetString("posts", response.ResponseBody[3]);
                    if(u.UserName.ToLower() != username.ToLower())
                    {
                        ViewBag.NotUser = true;
                    }else
                {
                    HttpContext.Session.SetString("profile", response.ResponseBody[0]);
                } 
                    return View("Account/Account");
            } else
            {
                return RedirectToAction("Login", "Home");
            }

        }

        //Send friend request from one user to another
        [HttpPost]
        public async Task<IActionResult> ProcessRelationshipRequest(string SecondUser, string RequestType, string RelationShipType)
        {
            if (HttpContext.Session.GetString("user") == null)
            {
                return RedirectToAction("Login", "Home");
            }

            UserViewModel firstUser = JsonConvert.DeserializeObject<UserViewModel>(HttpContext.Session.GetString("user"));

            RelationshipRequestModel relationshipRequest = new RelationshipRequestModel()
            {
                FirstUser = firstUser.UserName,
                SecondUser = SecondUser,
                RequestType = RequestType,
                RelationshipType = BVCommon.BVFunctions.RetrieveRelationshipType(RequestType)
            };

                HttpClient client = _api.Initial();
                var requestBody = new StringContent(JsonConvert.SerializeObject(relationshipRequest), Encoding.UTF8, "application/json");
                HttpResponseMessage result = await client.PostAsync("Post/RelationshipReq", requestBody);
                var r = result.Content.ReadAsStringAsync();

                if (r.IsCompletedSuccessfully)
                {
                    ApiResponseModel response = JsonConvert.DeserializeObject<ApiResponseModel>(r.Result);

                    if (result.ReasonPhrase == "OK")
                    {
                        return RedirectToAction("Profile", new { username = SecondUser }); // Return user to create their user account
                    }
                    else if (result.ReasonPhrase == "Conflict")
                    {
                        return RedirectToAction("Profile", new { username = SecondUser });
                    }
                    else
                    {
                        return RedirectToAction("Profile", new { username = SecondUser });
                    }
                }
                else
                {
                    // Log Error in ELog
                    Console.WriteLine("Error Occured");
                    return View("ConfirmEmail"); // Return user to Login Screen displaying an Error has occurred
                }
        }

        //Change User Profile Picture
        [HttpPost]
        public async Task<IActionResult> ChangeProfilePic(IFormFile profilePic)
        {
            if (HttpContext.Session.GetString("user") != null)
            {
                UserUpload userUpload = new UserUpload()
                {
                    userID = JsonConvert.DeserializeObject<Users>(HttpContext.Session.GetString("user")).UserId,
                    UploadFiles = new List<string>(),
                    FileNames = new List<string>(),
                    FileTypes = new List<string>()
                };

                userUpload.FileNames.Add(profilePic.FileName);
                userUpload.FileTypes.Add(profilePic.ContentType);

                using (var ms = new MemoryStream())
                {
                    profilePic.CopyTo(ms);
                    var fileBytes = ms.ToArray();
                    string s = Convert.ToBase64String(fileBytes);
                    userUpload.UploadFiles.Add(s);
                }
                    
                HttpClient client = _api.Initial();
                var requestBody = new StringContent(JsonConvert.SerializeObject(userUpload), Encoding.UTF8, "application/json");
                var result = await client.PostAsync("Post/UploadProfilePic", requestBody);
                var r = result.Content.ReadAsStringAsync();

                if (r.IsCompletedSuccessfully)
                {
                    if (result.ReasonPhrase == "OK")
                    {
                        return RedirectToAction("Account"); // Return user to create their user account
                    }
                    else if (result.ReasonPhrase == "Conflict")
                    {
                        return RedirectToAction("Account");
                    }
                    else
                    {
                        return RedirectToAction("Account");
                    }
                }
                else
                {

BibleVerse(Deprecated)/Views/BBV/Index.cshtml
@model BibleVerse.DTO.PostModel;
@using BibleVerse.DTO
@using Microsoft.AspNetCore.Http;
@using Newtonsoft.Json
@{
    Layout = "../Shared/_UserLayout.cshtml";
    ViewData["Title"] = "Home";
    UserViewModel user = JsonConvert.DeserializeObject<UserViewModel>(Context.Session.GetString("user"));
    List<Posts> tlPosts = new List<Posts>();
    
    if(Context.Session.GetString("posts") != "No Posts Found")
    {
        tlPosts = JsonConvert.DeserializeObject<List<Posts>>(Context.Session.GetString("posts"));
    }

}
<div class="container">
    <div id="upstat">
        <form class="form-group" asp-action="CreatePost" asp-controller="BBV" enctype="multipart/form-data">
            @using (Html.BeginForm("CreatePost", "BBV", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
               @Html.TextAreaFor(x => x.Body);
                <input type="file" name="IFiles" multiple />
                <input type="submit" value="Create Post" />
            }
        </form>
    </div>
    <div id="tl">
        @{
            foreach(Posts post in tlPosts)
            {
                <div id="@post.PostId" class="post">
                    <span><a asp-action="Profile" asp-controller="BBV" asp-route-username="@post.Username"><b>@post.Username</b></a></span> <span>@post.CreateDateTime.TimeOfDay</span>
                    <br/>

                    @{
                        if (post.Attachments != null)
                        {
                            List<PostsRelations> attachments = JsonConvert.DeserializeObject<List<PostsRelations>>(post.Attachments);

                            foreach (PostsRelations pr in attachments)
                            {
                                if (pr.ContentType == "Photo")
                                {
                                <img src="@pr.Link" height="300" width="300"/>
                                }
                                else
                                {
                                <video width="300" height="300" controls>
                                    <source src="@pr.Link" type="video/mp4">
                                </video>
                                    }
                                }
                            }
                        }
                    <p>@post.Body</p>
</div>
            }
        }
    </div>
</div>

BibleVerse(Deprecated)/Views/BBV/Search.cshtml
@using BibleVerse.DTO;
@using Newtonsoft.Json;
@using Microsoft.AspNetCore.Http;
@{
    Layout = "../Shared/_UserLayout.cshtml";
    ViewData["Title"] = "Search | BibleVerse";
    List<string> errors = new List<string>();
    List<SearchViewModel> searchResults = new List<SearchViewModel>();
    UserViewModel currUser = JsonConvert.DeserializeObject<UserViewModel>(Context.Session.GetString("user"));

    if (ViewBag.SearchResults != null)
    {
        searchResults = ViewBag.SearchResults;
    }

    if(ViewBag.Errors != null)
    {
        errors = ViewBag.Errors;
    }
}

<div class="container">
    @{
        if (ViewBag.SearchResults != null)
        {
            foreach(SearchViewModel s in searchResults)
            {
                <div class="searchResult/@searchResults.IndexOf(s)">
                    <img src="@s.PictureURL" />
                    <a asp-action="Profile" asp-controller="BBV" asp-route-username="@s.UserName"><p><b>@s.UserName</b></p></a>
                    <p class="lead">@s.OrgName</p>
                </div>
            }
        }else if(ViewBag.Errors != null)
        {
            foreach (string s in errors)
            {
                <p style="color: red;">@s</p>
            }
        }
    }
</div>